# Generated by Django 2.1 on 2018-08-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_extra',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='project',
            name='project_member',
            field=models.TextField(default='No one'),
        ),
    ]
